CREATE USER admin NOINHERIT NOBYPASSRLS PASSWORD 'postgres';
ALTER USER admin SET search_path TO my_schema;

-- スキーマを利用する権限を付与
GRANT USAGE ON SCHEMA my_schema TO admin;
-- スキーマ配下の全テーブルに対する権限を付与
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA my_schema TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA my_schema GRANT ALL PRIVILEGES ON TABLES TO admin;

-- スキーマ配下の全シーケンスに対する権限を付与
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA my_schema TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA my_schema GRANT ALL PRIVILEGES ON SEQUENCES TO admin;
