version: "3.9"
services:
  db:
    image: postgres:15.3
    restart: always

    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'kiririmode' # デフォルトのデータベース指定
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - ./sqls:/docker-entrypoint-initdb.d
