name: textlint
on:
  - pull_request

jobs:
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Setup Node Environment
        uses: actions/setup-node@v5
        with:
          node-version: "22"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Setup Reviewdog
        uses: reviewdog/action-setup@v1

      - name: Textlint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ${{ github.workspace }}/utils/textlint.sh
